w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  resources :articles

  get '/sessions/new', to: 'sessions#new', as: 'sign_in'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'
end

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Article

    if user
      can :create, Article
    end

    # can [:update, :destroy], Article do |article|
    #   user.id == article.user_id
    # end
    # alternate form:
    can [:update, :destroy], Article, :user_id => user.id

    if user.admin
      can :manage, Article
    end
  end
end

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
end

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :articles
end

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  
  private
  def current_user
    session[:current_user] ? User.find_by(id: session[:current_user]) : nil
  end

  def authenticate
    redirect_to sign_in_path unless current_user
  end
end

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def show
  end

  def new
  end

  def create
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end
end

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:current_user] = user.id
      redirect_to root_path
    else
      redirect_to sign_in_path
    end
  end

  def destroy
    session[:current_user] = nil
    redirect_to root_path
  end
end

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/views/articles/_article.html.erb
<div class="article">
  <h2 class="article-title"><%= article.title %></h2>
  <p class="article-content"><%= article.content %></p>
  <% if article.user %>
    <p class="article-author">By <%= article.user.username %></p>
  <% end %>
  <p class="article-links">
    <%= link_to_unless_current 'View', article %> |

    <% if can? :update, article %>
      <%= link_to 'Edit', edit_article_path(article) %> |
    <% end %>

    <% if can? :destroy, article %>
      <%= link_to 'Delete', article, method: :delete, data: {confirm: 'Are you sure?'} %>
    <% end %>
  </p>
</div>

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>

  <%= f.label :content %><br>
  <%= f.text_area :content %><br>

  <%= f.submit %>
<% end %>

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>
<%= link_to 'Back', @article %>

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/views/articles/index.html.erb
<h1>Articles</h1>
<%= render @articles %>

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/views/articles/show.html.erb
<h1>Articles</h1>
<%= link_to 'All Articles', articles_path %>
<%= render @article %>

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CancancanApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>
<% if current_user %>
  Welcome, <%= current_user.username %> |
  <%= link_to 'Sign Out', sessions_path, method: :delete %>
<% else %>
  <%= link_to 'Sign In', sign_in_path %>
<% end %>
</p>
<%= yield %>

</body>
</html>

w09/d02_cancancan_authorization/ex_cancancan/in-class/cancancan_app/app/views/welcome/home.html.erb
<h1>Home</h1>
<p>
  Welcome to the home page
</p>
<p>
  <a href="<%= articles_path %>">View all articles</a>
</p>